title: "own-repos-curator"
description: "own-repos-curator"
theme: jekyll-theme-slate
github:
  is_project_page: true
  repository_url: https://github.com/cat2151/own-repos-curator
plugins:
  - jekyll-sitemap
